name: Encrypt and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install StatiCrypt
        run: npm install -g staticrypt

      - name: Encrypt and prepare files
        run: |
          # 1. Create the 'dist' folder beforehand to ensure it exists
          mkdir -p dist

          # 2. Encrypt all HTML files at once
          staticrypt src/*.html \
            -d dist/ \
            -p "${{ secrets.STATICRYPT_PASSWORD }}" \
            --remember 7 \
            --template-button "Decriptează" \
            --template-color-primary "#4338CA" \
            --template-color-secondary "#EEF2FF" \
            --template-instructions '<link rel="icon" href="favicon.ico"><style>.staticrypt-form { border-radius: 12px !important; } #staticrypt-form > input { border-radius: 8px !important; }</style>' \
            --template-error "Parolă incorectă!" \
            --template-placeholder "Parolă" \
            --template-remember "Ține-mă minte" \
            --template-title "Pagină protejată" \
            --template-toggle-hide "Ascunde parola" \
            --template-toggle-show "Afișează parola"


          # 3. Copy the rest of the files (images, CSS), ignoring the already encrypted HTML files
          rsync -a --exclude="*.html" src/ dist/

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
